### ISSUE TITLE
can't compile on arduino 1.6.12

### ISSUE THREAD

**Issue by tanatt** [Links2004/arduinoVNC#7]
Hi guy.
I can't compile the demo sketch on arduino 1.6.12

it's having a lot of error related to lcd library.

here's some error message

 ```
C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In constructor 'Adafruit_ILI9341::Adafruit_ILI9341(int8_t, int8_t, int8_t, int8_t, int8_t, int8_t)':

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:30:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:31:3: error: '_dc' was not declared in this scope

   _dc   = dc;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:32:3: error: '_mosi' was not declared in this scope

   _mosi  = mosi;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:33:3: error: '_miso' was not declared in this scope

   _miso = miso;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:34:3: error: '_sclk' was not declared in this scope

   _sclk = sclk;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:35:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp: In constructor 'Adafruit_ILI9341::Adafruit_ILI9341(int8_t, int8_t, int8_t)':

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:43:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:44:3: error: '_dc' was not declared in this scope

   _dc   = dc;

   ^

C:\Users\tanatt\Documents\Arduino\libraries\Adafruit_ILI9341\Adafruit_ILI9341.cpp:45:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

> 
```

**Comment by Links2004** [comment]
you may use the wrong lib, try:
https://github.com/Links2004/Adafruit_ILI9341

I have done many optimizations to speed it up.
